'''
AUTHOR: Aditya Patel and Jim Ramsay
DATE CREATED: 2018-03-31
LAST MODIFIED:
PLATFORM: Raspberry Pi 3B, Raspbian Stretch Released 2017-11-29
PROJECT: EMG Human Machine Interface
ORGANIZATION: Bradley University, School of Electrical and Computer Engineering
FILENAME: videoControl.py
DESCRIPTION: 
	Script to control the display of the two different camera feeds. 
NOTE: 
	There is no logic needed in the switchDisplay() function, as this is a binary system. The main function will contain the logic. 
	
REFERENCES:
	[1] https://stackoverflow.com/questions/279561/what-is-the-python-equivalent-of-static-variables-inside-a-function
	
'''

import os														# used to execute shell commands
from time import sleep

def init():

	os.environ['DISPLAY'] = ":0"								# allows us to launch GUI applications and control the mouse. Limited to the scope of the call of this function. 
	os.system("killall firefox-esr")
	os.system("nohup firefox http://169.254.184.5/html/ &")		# 'nohup' -- ignore HANGUP signals generated by firefox (there are a ton)
	sleep(15)													
	os.system("nohup firefox http://169.254.13.230/html/ &")
	sleep(2)					
	os.system("xdotool key ctrl+Tab")							# Cycle tab to the "Restore session" tab that always comes up
	os.system("xdotool key ctrl+w")								# Close the tab
	sleep(3)		
	os.system("xdotool key F11")								# launch browswer in full screen
	sleep(3)		
	os.system("xdotool mousemove 600 200 &")					# enlarge camera 1
	sleep(0.1)
	os.system("xdotool click 1")
	sleep(0.1)
	os.system("xdotool key ctrl+Tab")
	sleep(3)
	os.system("xdotool click 1")								# enlarge camera 2
	os.system("xdotool key ctrl+Tab")	
	os.system("xdotool mousemove 0 500")						# Move mouse out of the way
	print("DISPLAY CONFIGURED")

def switchDisplay():
	
	switchDisplay.display ^= 1									# toggle variable between 0 and 1
	os.system("xdotool key ctrl+Tab")
	
	return(switchDisplay.display)

switchDisplay.display = 0										# initialize static variables

# Initialize
if __name__=='__main__':
	init()
	
	# sleep(1)
	# switchDisplay()
	# print("Attempting to change display")
	# sleep(5)
	# print("Attempting to change display")
	# switchDisplay()
